name: build
on:
  pull_request:
  push:
    branches:
    - main
jobs:
  build:
    name: build
    strategy:
      matrix:
        build:
        - linux-x86_64
        - linux-aarch64
        - macos-x86_64
        - macos-aarch64
        - windows
        include:
        - build: linux-x86_64
          os: ubuntu-18.04
          toolchain: stable
          target: x86_64-unknown-linux-musl
        - build: linux-aarch64
          os: ubuntu-18.04
          toolchain: stable
          target: aarch64-unknown-linux-musl
        - build: macos-x86_64
          os: macos-11
          toolchain: stable
          target: x86_64-apple-darwin
        - build: macos-aarch64
          os: macos-11
          toolchain: stable
          target: aarch64-apple-darwin
        - build: windows
          os: windows-2019
          toolchain: stable
          target: x86_64-pc-windows-msvc
    runs-on: ${{ matrix.os }}
    steps:

    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Install Rust
      uses: actions-rs/toolchain@v1
      with:
        toolchain: ${{ matrix.toolchain }}
        target: ${{ matrix.target }}
        profile: minimal
        override: true

    - name: Install Cross
      shell: bash
      run: cargo install cross

    - name: Build flightctl
      run: cross build --target "${{ matrix.target }}"
